# for github.com
approvals:
  # needed to keep the compliance checks happy
  groups:
    zalando:
      minimum: 2
      from:
        orgs:
          - zalando
    maintainers:
      minimum: 2
      from:
        users:
          - aermakov-zalando
          - gargravarr
          - jonathanbeber
          - katyanna
          - linki
          - mikkeloscar

X-Zalando-Team: teapot
X-Zalando-Type: code
