version: "2017-09-20"
pipeline:
- id: build
  overlay: ci/golang
  type: script
  working_dir: /go/src/k8s.io/autoscaler
  vm: large
  env:
    VERSION: "v0.9.2-internal"
  commands:
  - desc: "Build and release"
    cmd: |
      if [[ "${CDP_TARGET_BRANCH}" != "zalando-vertical-pod-autoscaler" || -n "${CDP_PULL_REQUEST_NUMBER}" ]]; then
        export TAG="${VERSION}.dev-${CDP_TARGET_REPOSITORY_COUNTER}"
      else
        export TAG="${VERSION}.${CDP_TARGET_BRANCH_COUNTER}"
      fi

      export REGISTRY=registry-write.opensource.zalan.do/teapot

      for f in admission-controller recommender updater; do
        (
          cd vertical-pod-autoscaler/pkg/$f
          ALL_ARCHITECTURES=amd64 make test-unit
          ALL_ARCHITECTURES=amd64 make build-in-docker
          ALL_ARCHITECTURES=amd64 make docker-build
          ALL_ARCHITECTURES=amd64 make sub-push-amd64
        )
      done
